[tool.poetry]
name = "governanceplatform"
version = "0.1.0"
description = "SERIMA Governance Platform"
authors = [
    "NC3 Team <info@nc3.lu>",
]
license = "AGPL-3.0-or-later"
readme = "README.md"

homepage = "https://github.com/informed-governance-project/governance-platform"
repository = "https://github.com/informed-governance-project/governance-platform"
documentation = "https://serima.readthedocs.io"

keywords = ["NC3-LU", "NIS", "NIS2", "incident-notification"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2"
psycopg2-binary = "^2.8.4"
cryptography = "^41.0.3"
django-cors-headers = "^3.14.0"
drf-spectacular = "^0.26.1"
drf-spectacular-sidecar = "^2023.4.1"
django-bootstrap5 = "^23.1"
django-otp = "^1.1.6"
django-formtools = "^2.4"
django-two-factor-auth = "^1.15.2"
phonenumbers = "^8.13.11"
django-import-export = "^3.2.0"
parler = "^1.0.1"
django-parler = "^2.3"
django-bootstrap-datepicker-plus = "^5.0.4"
django-countries = "^7.5.1"


[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
pre-commit = "^2.20.0"
black = "^22.10.0"
pyupgrade = "^3.2.2"
autoflake = "^1.7.7"
mypy = "^0.991"
types-requests = "^2.28.11.5"
pip-audit = "^2.5.4"
isort = "^5.12.0"
django-debug-toolbar = "^4.0.0"
sphinx-book-theme = "^0.3.2"
sphinx-autodoc-typehints = "^1.18.3"
pyparsing = "^3.1.1"
pydot = "^1.4.2"
django-extensions = "^3.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
strict_optional = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true

show_error_context = true
pretty = true
