openapi: 3.0.3
info:
  title: NC3-LU Governance Platform
  version: 1.0.0
  description: API for the <a href="https://github.com/informed-governance-project"
    rel="noopener noreferrer" target="_blank">Governance Platform</a> by NC3-LU.
paths: {}
components: {}
